### ISSUE TITLE
Rechte

### ISSUE THREAD

**Issue by DelloxD1** [pybi/schoolproject-v0.01#1]
wir müssen das dann noch irgendiwe hinbekommen dass ich auch uploadrechte habe, denn die habe ich momentan noch nicht :/

marc

**Comment by HHimbergen** [comment]
Hey Marc,
generell müsstest du nicht einmal die nötigen Rechte haben, wobei ich das begrüßen würde.
Änderungen können über den sog. Pull Request verbreitet werden. (Davor musst du aber auch das Repository forken :+1:)

- Dennis
