### ISSUE TITLE
Coderichtlinien für LUA

### ISSUE THREAD

**Issue by HHimbergen** [pybi/schoolproject-v0.01#3]
Bitte haltet euch dran, um die Lesbarkeit des Codes zu erhöhen.
Zudem bekommt jede Funktion einen Kommentar und evtl. (falls komplex) einen Eintrag im Wiki!

Coding-Standards for LUA:
http://lua-users.org/wiki/LuaStyleGuide

**Comment by pybi** [comment]
und er beschwert sich das es bei der visoma zu viele Richtlinien gibt :laughing:

**Comment by HHimbergen** [comment]
Aber dieeeeeeeeeeee sind ja auch unnötig. :laughing:
